# -*- coding: utf-8 -*-
# Generated by Django 1.11.15.dev20180729042848 on 2020-05-02 14:51
from __future__ import unicode_literals
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

from future import standard_library
standard_library.install_aliases()
from builtins import *
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personnel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userhistory',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userhistory',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
